[2023-02-27T15:39:56.455+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: first_dag.inaccurate manual__2023-02-27T15:39:52.915495+00:00 [queued]>
[2023-02-27T15:39:56.464+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: first_dag.inaccurate manual__2023-02-27T15:39:52.915495+00:00 [queued]>
[2023-02-27T15:39:56.464+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T15:39:56.465+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-27T15:39:56.465+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T15:39:56.474+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): inaccurate> on 2023-02-27 15:39:52.915495+00:00
[2023-02-27T15:39:56.478+0000] {standard_task_runner.py:55} INFO - Started process 20188 to run task
[2023-02-27T15:39:56.481+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'inaccurate', 'manual__2023-02-27T15:39:52.915495+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpb2xt0aby']
[2023-02-27T15:39:56.482+0000] {standard_task_runner.py:83} INFO - Job 59: Subtask inaccurate
[2023-02-27T15:39:56.538+0000] {task_command.py:388} INFO - Running <TaskInstance: first_dag.inaccurate manual__2023-02-27T15:39:52.915495+00:00 [running]> on host f7c6263a9b51
[2023-02-27T15:39:56.586+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2023-02-27T15:39:52.915495+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-27T15:39:52.915495+00:00
[2023-02-27T15:39:56.587+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-27T15:39:56.588+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2023-02-27T15:39:56.599+0000] {subprocess.py:86} INFO - Output:
[2023-02-27T15:39:56.601+0000] {subprocess.py:93} INFO - inaccurate
[2023-02-27T15:39:56.602+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-02-27T15:39:56.624+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=inaccurate, execution_date=20230227T153952, start_date=20230227T153956, end_date=20230227T153956
[2023-02-27T15:39:56.654+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-02-27T15:39:56.669+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
