[2023-02-27T08:32:45.299+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:32:45.303+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:32:45.307+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:32:45.306+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:32:45.360+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:32:45.380+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.088 seconds
[2023-02-27T08:32:47.444+0000] {processor.py:153} INFO - Started process (PID=36) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:32:47.446+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:32:47.448+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:32:47.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:32:47.457+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:32:47.455+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 5
    with dags
            ^
SyntaxError: invalid syntax
[2023-02-27T08:32:47.458+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:32:47.513+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.081 seconds
[2023-02-27T08:33:02.661+0000] {processor.py:153} INFO - Started process (PID=61) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:02.663+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:33:02.665+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:33:02.665+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:02.671+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:33:02.670+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7
    )
    ^
SyntaxError: invalid syntax
[2023-02-27T08:33:02.672+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:02.693+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.035 seconds
[2023-02-27T08:33:08.742+0000] {processor.py:153} INFO - Started process (PID=62) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:08.745+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:33:08.747+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:33:08.747+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:08.757+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:33:08.756+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7
    )
    ^
SyntaxError: invalid syntax
[2023-02-27T08:33:08.759+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:08.787+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.051 seconds
[2023-02-27T08:33:15.804+0000] {processor.py:153} INFO - Started process (PID=74) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:15.805+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:33:15.806+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:33:15.806+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:15.812+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:33:15.811+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7
    )
    ^
SyntaxError: invalid syntax
[2023-02-27T08:33:15.813+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:15.836+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.035 seconds
[2023-02-27T08:33:33.069+0000] {processor.py:153} INFO - Started process (PID=87) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:33.074+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:33:33.076+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:33:33.076+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:33.089+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:33:33.088+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2023-02-27T08:33:33.090+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:33.119+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.055 seconds
[2023-02-27T08:33:39.146+0000] {processor.py:153} INFO - Started process (PID=100) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:39.148+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:33:39.149+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:33:39.149+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:39.163+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:33:39.161+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2023-02-27T08:33:39.165+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:39.187+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.047 seconds
[2023-02-27T08:33:50.296+0000] {processor.py:153} INFO - Started process (PID=114) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:50.298+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:33:50.299+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:33:50.299+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:50.305+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:33:50.304+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2023-02-27T08:33:50.306+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:50.329+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.038 seconds
[2023-02-27T08:33:59.360+0000] {processor.py:153} INFO - Started process (PID=128) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:59.362+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:33:59.363+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:33:59.362+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:59.368+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:33:59.368+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2023-02-27T08:33:59.369+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:33:59.391+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.033 seconds
[2023-02-27T08:34:06.423+0000] {processor.py:153} INFO - Started process (PID=129) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:34:06.425+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:34:06.426+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:34:06.426+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:34:06.436+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:34:06.434+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 9
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-02-27T08:34:06.437+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:34:06.463+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.047 seconds
[2023-02-27T08:34:36.771+0000] {processor.py:153} INFO - Started process (PID=167) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:34:36.775+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:34:36.777+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:34:36.777+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:34:36.786+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:34:36.785+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 9
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-02-27T08:34:36.788+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:34:36.811+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.047 seconds
[2023-02-27T08:34:51.052+0000] {processor.py:153} INFO - Started process (PID=182) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:34:51.055+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:34:51.057+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:34:51.057+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:34:51.068+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:34:51.066+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 10
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-02-27T08:34:51.069+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:34:51.093+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.047 seconds
[2023-02-27T08:34:58.141+0000] {processor.py:153} INFO - Started process (PID=195) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:34:58.143+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:34:58.144+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:34:58.144+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:34:58.165+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:34:58.163+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:34:58.166+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:34:58.190+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.053 seconds
[2023-02-27T08:35:02.211+0000] {processor.py:153} INFO - Started process (PID=196) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:02.213+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:35:02.214+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:35:02.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:02.223+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:35:02.221+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 10
    waiting_for_file =
                      ^
SyntaxError: invalid syntax
[2023-02-27T08:35:02.224+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:02.254+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.049 seconds
[2023-02-27T08:35:14.380+0000] {processor.py:153} INFO - Started process (PID=209) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:14.382+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:35:14.383+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:35:14.383+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:14.397+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:35:14.395+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:35:14.398+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:14.415+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.037 seconds
[2023-02-27T08:35:21.516+0000] {processor.py:153} INFO - Started process (PID=223) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:21.519+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:35:21.522+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:35:21.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:21.545+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:35:21.544+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:35:21.546+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:21.569+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.057 seconds
[2023-02-27T08:35:50.900+0000] {processor.py:153} INFO - Started process (PID=249) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:50.903+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:35:50.905+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:35:50.905+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:50.935+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:35:50.913+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2023-02-27T08:35:50.937+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:50.972+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.076 seconds
[2023-02-27T08:35:54.963+0000] {processor.py:153} INFO - Started process (PID=262) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:54.964+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:35:54.965+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:35:54.965+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:54.982+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:35:54.981+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:35:54.984+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:35:55.007+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.048 seconds
[2023-02-27T08:36:25.305+0000] {processor.py:153} INFO - Started process (PID=289) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:36:25.307+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:36:25.308+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:36:25.308+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:36:25.318+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:36:25.316+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:36:25.322+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:36:25.341+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.039 seconds
[2023-02-27T08:36:55.594+0000] {processor.py:153} INFO - Started process (PID=327) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:36:55.598+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:36:55.599+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:36:55.599+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:36:55.615+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:36:55.612+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:36:55.616+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:36:55.637+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.049 seconds
[2023-02-27T08:37:25.966+0000] {processor.py:153} INFO - Started process (PID=365) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:37:25.970+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:37:25.972+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:37:25.972+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:37:25.986+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:37:25.984+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:37:25.987+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:37:26.007+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.050 seconds
[2023-02-27T08:37:56.371+0000] {processor.py:153} INFO - Started process (PID=391) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:37:56.375+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:37:56.377+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:37:56.377+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:37:56.389+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:37:56.387+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:37:56.390+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:37:56.409+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.045 seconds
[2023-02-27T08:38:26.620+0000] {processor.py:153} INFO - Started process (PID=429) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:38:26.622+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:38:26.622+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:38:26.622+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:38:26.629+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:38:26.628+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:38:26.630+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:38:26.646+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.030 seconds
[2023-02-27T08:38:56.960+0000] {processor.py:153} INFO - Started process (PID=466) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:38:56.964+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:38:56.967+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:38:56.966+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:38:56.982+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:38:56.980+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:38:56.984+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:38:57.013+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.059 seconds
[2023-02-27T08:39:27.293+0000] {processor.py:153} INFO - Started process (PID=492) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:39:27.297+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:39:27.298+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:39:27.298+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:39:27.309+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:39:27.307+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:39:27.311+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:39:27.331+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.043 seconds
[2023-02-27T08:39:57.594+0000] {processor.py:153} INFO - Started process (PID=530) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:39:57.596+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:39:57.597+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:39:57.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:39:57.609+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:39:57.607+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:39:57.609+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:39:57.627+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.039 seconds
[2023-02-27T08:40:27.945+0000] {processor.py:153} INFO - Started process (PID=567) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:40:27.947+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:40:27.949+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:40:27.949+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:40:27.963+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:40:27.961+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:40:27.964+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:40:27.987+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.049 seconds
[2023-02-27T08:40:58.315+0000] {processor.py:153} INFO - Started process (PID=593) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:40:58.317+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:40:58.319+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:40:58.318+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:40:58.330+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:40:58.328+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:40:58.331+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:40:58.353+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.044 seconds
[2023-02-27T08:41:28.602+0000] {processor.py:153} INFO - Started process (PID=630) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:41:28.604+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:41:28.605+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:41:28.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:41:28.615+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:41:28.613+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:41:28.616+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:41:28.636+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.037 seconds
[2023-02-27T08:41:58.873+0000] {processor.py:153} INFO - Started process (PID=667) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:41:58.874+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:41:58.876+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:41:58.876+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:41:58.886+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:41:58.884+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:41:58.887+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:41:58.909+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.041 seconds
[2023-02-27T08:42:29.171+0000] {processor.py:153} INFO - Started process (PID=701) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:42:29.172+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:42:29.173+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:42:29.173+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:42:29.180+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:42:29.179+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:42:29.181+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:42:29.198+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.030 seconds
[2023-02-27T08:42:48.366+0000] {processor.py:153} INFO - Started process (PID=717) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:42:48.368+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:42:48.369+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:42:48.369+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:42:48.387+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:42:48.385+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:42:48.388+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:42:48.422+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.061 seconds
[2023-02-27T08:43:18.771+0000] {processor.py:153} INFO - Started process (PID=756) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:43:18.773+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:43:18.774+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:43:18.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:43:18.783+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:43:18.781+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:43:18.784+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:43:18.802+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.034 seconds
[2023-02-27T08:43:49.149+0000] {processor.py:153} INFO - Started process (PID=791) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:43:49.151+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:43:49.152+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:43:49.152+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:43:49.162+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:43:49.160+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:43:49.163+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:43:49.184+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.038 seconds
[2023-02-27T08:44:19.490+0000] {processor.py:153} INFO - Started process (PID=820) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:44:19.492+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:44:19.494+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:44:19.494+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:44:19.507+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:44:19.505+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:44:19.508+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:44:19.527+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.043 seconds
[2023-02-27T08:44:49.806+0000] {processor.py:153} INFO - Started process (PID=859) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:44:49.808+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:44:49.809+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:44:49.809+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:44:49.818+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:44:49.817+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:44:49.819+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:44:49.842+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.040 seconds
[2023-02-27T08:45:20.145+0000] {processor.py:153} INFO - Started process (PID=893) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:45:20.147+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:45:20.148+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:45:20.147+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:45:20.156+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:45:20.154+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:45:20.156+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:45:20.173+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.030 seconds
[2023-02-27T08:45:50.510+0000] {processor.py:153} INFO - Started process (PID=922) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:45:50.512+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:45:50.513+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:45:50.513+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:45:50.522+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:45:50.521+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:45:50.524+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:45:50.542+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.036 seconds
[2023-02-27T08:46:20.858+0000] {processor.py:153} INFO - Started process (PID=961) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:46:20.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:46:20.863+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:46:20.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:46:20.878+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:46:20.876+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:46:20.880+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:46:20.906+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.053 seconds
[2023-02-27T08:46:51.225+0000] {processor.py:153} INFO - Started process (PID=999) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:46:51.226+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:46:51.227+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:46:51.227+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:46:51.234+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:46:51.233+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:46:51.235+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:46:51.250+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.027 seconds
[2023-02-27T08:47:21.502+0000] {processor.py:153} INFO - Started process (PID=1025) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:47:21.504+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:47:21.505+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:47:21.505+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:47:21.513+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:47:21.512+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:47:21.514+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:47:21.532+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.035 seconds
[2023-02-27T08:47:51.853+0000] {processor.py:153} INFO - Started process (PID=1063) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:47:51.855+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:47:51.856+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:47:51.856+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:47:51.864+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:47:51.862+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:47:51.865+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:47:51.884+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.034 seconds
[2023-02-27T08:48:22.223+0000] {processor.py:153} INFO - Started process (PID=1101) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:48:22.225+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:48:22.226+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:48:22.226+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:48:22.233+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:48:22.231+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:48:22.233+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:48:22.248+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.027 seconds
[2023-02-27T08:48:52.577+0000] {processor.py:153} INFO - Started process (PID=1127) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:48:52.579+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:48:52.581+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:48:52.581+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:48:52.597+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:48:52.594+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:48:52.598+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:48:52.628+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.057 seconds
[2023-02-27T08:49:22.984+0000] {processor.py:153} INFO - Started process (PID=1165) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:49:22.986+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:49:22.988+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:49:22.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:49:23.002+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:49:22.999+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:49:23.003+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:49:23.029+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.051 seconds
[2023-02-27T08:49:53.371+0000] {processor.py:153} INFO - Started process (PID=1202) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:49:53.372+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:49:53.373+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:49:53.373+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:49:53.381+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:49:53.380+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:49:53.382+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:49:53.399+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.031 seconds
[2023-02-27T08:50:23.685+0000] {processor.py:153} INFO - Started process (PID=1229) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:50:23.689+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:50:23.691+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:50:23.690+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:50:23.705+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:50:23.702+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:50:23.707+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:50:23.730+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.050 seconds
[2023-02-27T08:50:54.048+0000] {processor.py:153} INFO - Started process (PID=1267) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:50:54.049+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:50:54.050+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:50:54.050+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:50:54.060+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:50:54.059+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:50:54.061+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:50:54.086+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.042 seconds
[2023-02-27T08:51:24.420+0000] {processor.py:153} INFO - Started process (PID=1305) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:51:24.424+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:51:24.425+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:51:24.425+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:51:24.439+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:51:24.437+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:51:24.440+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:51:24.462+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.048 seconds
[2023-02-27T08:51:54.760+0000] {processor.py:153} INFO - Started process (PID=1330) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:51:54.762+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:51:54.763+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:51:54.763+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:51:54.772+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:51:54.771+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:51:54.774+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:51:54.793+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.036 seconds
[2023-02-27T08:52:25.126+0000] {processor.py:153} INFO - Started process (PID=1368) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:52:25.131+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:52:25.133+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:52:25.133+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:52:25.144+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:52:25.142+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:52:25.145+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:52:25.169+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.049 seconds
[2023-02-27T08:52:55.539+0000] {processor.py:153} INFO - Started process (PID=1407) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:52:55.542+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:52:55.543+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:52:55.543+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:52:55.554+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:52:55.552+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:52:55.556+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:52:55.574+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.040 seconds
[2023-02-27T08:53:25.925+0000] {processor.py:153} INFO - Started process (PID=1433) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:53:25.929+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:53:25.931+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:53:25.931+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:53:25.946+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:53:25.945+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:53:25.948+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:53:25.967+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.050 seconds
[2023-02-27T08:53:56.293+0000] {processor.py:153} INFO - Started process (PID=1471) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:53:56.297+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:53:56.298+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:53:56.298+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:53:56.314+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:53:56.311+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:53:56.315+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:53:56.341+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.054 seconds
[2023-02-27T08:54:12.570+0000] {processor.py:153} INFO - Started process (PID=1484) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:54:12.572+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:54:12.574+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:54:12.574+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:54:12.605+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:54:12.601+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:54:12.605+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:54:12.637+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.073 seconds
[2023-02-27T08:54:42.957+0000] {processor.py:153} INFO - Started process (PID=1522) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:54:42.960+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:54:42.962+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:54:42.962+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:54:42.975+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:54:42.973+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:54:42.975+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:54:42.996+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.043 seconds
[2023-02-27T08:55:13.327+0000] {processor.py:153} INFO - Started process (PID=1559) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:55:13.331+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:55:13.333+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:55:13.333+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:55:13.348+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:55:13.346+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:55:13.350+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:55:13.373+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.052 seconds
[2023-02-27T08:55:43.642+0000] {processor.py:153} INFO - Started process (PID=1585) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:55:43.644+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:55:43.645+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:55:43.645+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:55:43.653+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:55:43.651+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:55:43.654+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:55:43.672+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.033 seconds
[2023-02-27T08:56:13.991+0000] {processor.py:153} INFO - Started process (PID=1624) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:56:13.994+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:56:13.995+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:56:13.995+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:56:14.008+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:56:14.005+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:56:14.008+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:56:14.027+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.041 seconds
[2023-02-27T08:56:44.402+0000] {processor.py:153} INFO - Started process (PID=1664) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:56:44.404+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:56:44.406+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:56:44.406+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:56:44.420+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:56:44.417+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:56:44.421+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:56:44.450+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.052 seconds
[2023-02-27T08:57:14.761+0000] {processor.py:153} INFO - Started process (PID=1690) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:57:14.763+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:57:14.765+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:57:14.765+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:57:14.778+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:57:14.776+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:57:14.779+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:57:14.798+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.043 seconds
[2023-02-27T08:57:45.119+0000] {processor.py:153} INFO - Started process (PID=1728) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:57:45.121+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:57:45.121+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:57:45.121+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:57:45.129+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:57:45.127+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:57:45.129+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:57:45.146+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.030 seconds
[2023-02-27T08:58:15.480+0000] {processor.py:153} INFO - Started process (PID=1766) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:58:15.482+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:58:15.484+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:58:15.484+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:58:15.491+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:58:15.490+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:58:15.492+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:58:15.507+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.030 seconds
[2023-02-27T08:58:45.734+0000] {processor.py:153} INFO - Started process (PID=1798) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:58:45.735+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:58:45.736+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:58:45.736+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:58:45.743+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:58:45.742+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:58:45.744+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:58:45.760+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.029 seconds
[2023-02-27T08:59:16.109+0000] {processor.py:153} INFO - Started process (PID=1828) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:59:16.112+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:59:16.113+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:59:16.113+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:59:16.127+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:59:16.125+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:59:16.128+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:59:16.146+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.044 seconds
[2023-02-27T08:59:46.481+0000] {processor.py:153} INFO - Started process (PID=1866) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:59:46.484+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T08:59:46.485+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:59:46.485+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:59:46.495+0000] {logging_mixin.py:137} INFO - [2023-02-27T08:59:46.494+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T08:59:46.496+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T08:59:46.514+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.039 seconds
[2023-02-27T09:00:16.821+0000] {processor.py:153} INFO - Started process (PID=1901) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:00:16.823+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:00:16.826+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:00:16.826+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:00:16.836+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:00:16.834+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:00:16.836+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:00:16.853+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.035 seconds
[2023-02-27T09:00:47.217+0000] {processor.py:153} INFO - Started process (PID=1931) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:00:47.220+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:00:47.221+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:00:47.221+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:00:47.235+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:00:47.233+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:00:47.236+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:00:47.260+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.048 seconds
[2023-02-27T09:01:17.487+0000] {processor.py:153} INFO - Started process (PID=1970) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:01:17.488+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:01:17.489+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:01:17.489+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:01:17.496+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:01:17.495+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:01:17.497+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:01:17.515+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.030 seconds
[2023-02-27T09:01:47.809+0000] {processor.py:153} INFO - Started process (PID=2008) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:01:47.811+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:01:47.812+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:01:47.811+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:01:47.820+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:01:47.817+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:01:47.821+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:01:47.839+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.033 seconds
[2023-02-27T09:02:18.101+0000] {processor.py:153} INFO - Started process (PID=2034) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:02:18.103+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:02:18.104+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:02:18.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:02:18.113+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:02:18.111+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:02:18.114+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:02:18.134+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.038 seconds
[2023-02-27T09:02:48.404+0000] {processor.py:153} INFO - Started process (PID=2073) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:02:48.406+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:02:48.407+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:02:48.407+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:02:48.413+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:02:48.412+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:02:48.414+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:02:48.431+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.029 seconds
[2023-02-27T09:03:18.651+0000] {processor.py:153} INFO - Started process (PID=2110) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:03:18.652+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:03:18.653+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:03:18.653+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:03:18.661+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:03:18.659+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:03:18.661+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:03:18.679+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.030 seconds
[2023-02-27T09:03:48.953+0000] {processor.py:153} INFO - Started process (PID=2136) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:03:48.955+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:03:48.956+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:03:48.956+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:03:48.966+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:03:48.964+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:03:48.966+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:03:48.988+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.038 seconds
[2023-02-27T09:04:19.372+0000] {processor.py:153} INFO - Started process (PID=2174) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:04:19.375+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:04:19.377+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:04:19.377+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:04:19.391+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:04:19.388+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:04:19.392+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:04:19.416+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.052 seconds
[2023-02-27T09:04:49.749+0000] {processor.py:153} INFO - Started process (PID=2213) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:04:49.751+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:04:49.752+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:04:49.752+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:04:49.778+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:04:49.776+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:04:49.779+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:04:49.796+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.073 seconds
[2023-02-27T09:05:20.124+0000] {processor.py:153} INFO - Started process (PID=2238) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:05:20.125+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:05:20.126+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:05:20.126+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:05:20.134+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:05:20.133+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:05:20.135+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:05:20.152+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.032 seconds
[2023-02-27T09:05:50.438+0000] {processor.py:153} INFO - Started process (PID=2278) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:05:50.439+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:05:50.440+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:05:50.440+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:05:50.448+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:05:50.447+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:05:50.449+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:05:50.468+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.033 seconds
[2023-02-27T09:06:20.759+0000] {processor.py:153} INFO - Started process (PID=2317) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:06:20.763+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:06:20.765+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:06:20.765+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:06:20.785+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:06:20.783+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:06:20.785+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:06:20.813+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.057 seconds
[2023-02-27T09:06:51.164+0000] {processor.py:153} INFO - Started process (PID=2342) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:06:51.167+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:06:51.169+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:06:51.169+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:06:51.184+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:06:51.182+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:06:51.185+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:06:51.206+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.048 seconds
[2023-02-27T09:07:21.453+0000] {processor.py:153} INFO - Started process (PID=2381) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:07:21.454+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:07:21.455+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:07:21.455+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:07:21.463+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:07:21.462+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:07:21.464+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:07:21.483+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.034 seconds
[2023-02-27T09:07:51.744+0000] {processor.py:153} INFO - Started process (PID=2419) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:07:51.745+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:07:51.746+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:07:51.746+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:07:51.753+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:07:51.752+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:07:51.753+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:07:51.769+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.028 seconds
[2023-02-27T09:08:22.063+0000] {processor.py:153} INFO - Started process (PID=2444) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:08:22.065+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:08:22.066+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:08:22.066+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:08:22.079+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:08:22.077+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:08:22.080+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:08:22.097+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.038 seconds
[2023-02-27T09:08:52.425+0000] {processor.py:153} INFO - Started process (PID=2481) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:08:52.429+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:08:52.430+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:08:52.430+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:08:52.441+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:08:52.440+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:08:52.442+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:08:52.461+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.041 seconds
[2023-02-27T09:09:22.718+0000] {processor.py:153} INFO - Started process (PID=2519) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:09:22.719+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:09:22.720+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:09:22.720+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:09:22.730+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:09:22.728+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:09:22.730+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:09:22.749+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.035 seconds
[2023-02-27T09:09:53.125+0000] {processor.py:153} INFO - Started process (PID=2545) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:09:53.128+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:09:53.129+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:09:53.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:09:53.137+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:09:53.135+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:09:53.138+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:09:53.157+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.035 seconds
[2023-02-27T09:10:23.523+0000] {processor.py:153} INFO - Started process (PID=2584) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:10:23.527+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:10:23.529+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:10:23.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:10:23.543+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:10:23.540+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:10:23.544+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:10:23.564+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.047 seconds
[2023-02-27T09:10:53.867+0000] {processor.py:153} INFO - Started process (PID=2622) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:10:53.868+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:10:53.869+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:10:53.869+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:10:53.876+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:10:53.875+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:10:53.876+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:10:53.892+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.029 seconds
[2023-02-27T09:11:24.275+0000] {processor.py:153} INFO - Started process (PID=2648) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:11:24.277+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:11:24.280+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:11:24.280+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:11:24.290+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:11:24.288+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:11:24.291+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:11:24.310+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.042 seconds
[2023-02-27T09:11:54.540+0000] {processor.py:153} INFO - Started process (PID=2687) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:11:54.543+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:11:54.545+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:11:54.544+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:11:54.560+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:11:54.558+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:11:54.561+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:11:54.580+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.047 seconds
[2023-02-27T09:12:24.831+0000] {processor.py:153} INFO - Started process (PID=2725) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:12:24.834+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:12:24.835+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:12:24.834+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:12:24.845+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:12:24.842+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:12:24.846+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:12:24.880+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.052 seconds
[2023-02-27T09:12:55.234+0000] {processor.py:153} INFO - Started process (PID=2751) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:12:55.235+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:12:55.237+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:12:55.237+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:12:55.246+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:12:55.245+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:12:55.247+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:12:55.270+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.040 seconds
[2023-02-27T09:13:25.524+0000] {processor.py:153} INFO - Started process (PID=2788) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:13:25.526+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:13:25.527+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:13:25.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:13:25.535+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:13:25.534+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:13:25.536+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:13:25.554+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.034 seconds
[2023-02-27T09:13:55.808+0000] {processor.py:153} INFO - Started process (PID=2826) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:13:55.811+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:13:55.812+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:13:55.812+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:13:55.824+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:13:55.822+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:13:55.825+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:13:55.849+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.045 seconds
[2023-02-27T09:14:26.238+0000] {processor.py:153} INFO - Started process (PID=2852) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:14:26.243+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:14:26.245+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:14:26.244+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:14:26.257+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:14:26.255+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:14:26.258+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:14:26.278+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.046 seconds
[2023-02-27T09:14:56.570+0000] {processor.py:153} INFO - Started process (PID=2889) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:14:56.573+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:14:56.575+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:14:56.575+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:14:56.588+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:14:56.586+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:14:56.590+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:14:56.609+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.045 seconds
[2023-02-27T09:15:26.875+0000] {processor.py:153} INFO - Started process (PID=2927) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:15:26.876+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:15:26.878+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:15:26.878+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:15:26.891+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:15:26.890+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:15:26.893+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:15:26.910+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.040 seconds
[2023-02-27T09:15:57.280+0000] {processor.py:153} INFO - Started process (PID=2954) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:15:57.283+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:15:57.284+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:15:57.284+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:15:57.300+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:15:57.297+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:15:57.301+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:15:57.324+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.052 seconds
[2023-02-27T09:16:27.610+0000] {processor.py:153} INFO - Started process (PID=2992) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:16:27.612+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:16:27.613+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:16:27.613+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:16:27.621+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:16:27.619+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:16:27.622+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:16:27.640+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.034 seconds
[2023-02-27T09:16:57.947+0000] {processor.py:153} INFO - Started process (PID=3031) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:16:57.952+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:16:57.954+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:16:57.954+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:16:57.968+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:16:57.966+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:16:57.969+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:16:57.988+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.047 seconds
[2023-02-27T09:17:28.352+0000] {processor.py:153} INFO - Started process (PID=3058) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:17:28.353+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:17:28.354+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:17:28.354+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:17:28.362+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:17:28.360+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:17:28.362+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:17:28.379+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.029 seconds
[2023-02-27T09:17:58.715+0000] {processor.py:153} INFO - Started process (PID=3096) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:17:58.717+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:17:58.719+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:17:58.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:17:58.730+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:17:58.729+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:17:58.731+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:17:58.759+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.047 seconds
[2023-02-27T09:18:29.075+0000] {processor.py:153} INFO - Started process (PID=3133) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:18:29.079+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:18:29.081+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:18:29.081+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:18:29.097+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:18:29.094+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:18:29.099+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:18:29.125+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.056 seconds
[2023-02-27T09:18:59.424+0000] {processor.py:153} INFO - Started process (PID=3159) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:18:59.426+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:18:59.427+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:18:59.427+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:18:59.434+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:18:59.433+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:18:59.435+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:18:59.452+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.031 seconds
[2023-02-27T09:19:29.750+0000] {processor.py:153} INFO - Started process (PID=3196) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:19:29.753+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:19:29.755+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:19:29.755+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:19:29.770+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:19:29.768+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:19:29.772+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:19:29.800+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.055 seconds
[2023-02-27T09:20:00.198+0000] {processor.py:153} INFO - Started process (PID=3234) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:20:00.200+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:20:00.202+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:20:00.202+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:20:00.221+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:20:00.219+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:20:00.223+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:20:00.247+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.056 seconds
[2023-02-27T09:20:30.529+0000] {processor.py:153} INFO - Started process (PID=3259) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:20:30.532+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:20:30.533+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:20:30.532+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:20:30.541+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:20:30.540+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:20:30.542+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:20:30.559+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.034 seconds
[2023-02-27T09:21:00.900+0000] {processor.py:153} INFO - Started process (PID=3297) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:21:00.903+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:21:00.905+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:21:00.905+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:21:00.919+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:21:00.917+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:21:00.921+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:21:00.948+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.054 seconds
[2023-02-27T09:21:31.218+0000] {processor.py:153} INFO - Started process (PID=3335) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:21:31.221+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:21:31.222+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:21:31.222+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:21:31.231+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:21:31.230+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:21:31.232+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:21:31.253+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.039 seconds
[2023-02-27T09:22:01.526+0000] {processor.py:153} INFO - Started process (PID=3361) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:22:01.528+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:22:01.529+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:22:01.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:22:01.540+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:22:01.538+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:22:01.541+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:22:01.564+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.042 seconds
[2023-02-27T09:22:31.867+0000] {processor.py:153} INFO - Started process (PID=3399) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:22:31.869+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:22:31.871+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:22:31.871+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:22:31.879+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:22:31.877+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:22:31.879+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:22:31.895+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.033 seconds
[2023-02-27T09:23:02.157+0000] {processor.py:153} INFO - Started process (PID=3437) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:23:02.159+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:23:02.160+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:23:02.160+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:23:02.169+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:23:02.167+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:23:02.170+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:23:02.191+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.037 seconds
[2023-02-27T09:23:32.465+0000] {processor.py:153} INFO - Started process (PID=3462) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:23:32.467+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:23:32.469+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:23:32.469+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:23:32.479+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:23:32.477+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:23:32.479+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:23:32.502+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.040 seconds
[2023-02-27T09:24:02.727+0000] {processor.py:153} INFO - Started process (PID=3500) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:24:02.729+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:24:02.731+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:24:02.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:24:02.743+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:24:02.742+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:24:02.744+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:24:02.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.040 seconds
[2023-02-27T09:24:33.002+0000] {processor.py:153} INFO - Started process (PID=3538) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:24:33.005+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:24:33.006+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:24:33.006+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:24:33.015+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:24:33.014+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:24:33.016+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:24:33.033+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.035 seconds
[2023-02-27T09:25:03.306+0000] {processor.py:153} INFO - Started process (PID=3564) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:25:03.307+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:25:03.308+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:25:03.308+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:25:03.320+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:25:03.318+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:25:03.321+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:25:03.344+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.042 seconds
[2023-02-27T09:25:33.562+0000] {processor.py:153} INFO - Started process (PID=3602) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:25:33.563+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:25:33.564+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:25:33.564+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:25:33.574+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:25:33.573+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:25:33.575+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:25:33.596+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.038 seconds
[2023-02-27T09:26:03.827+0000] {processor.py:153} INFO - Started process (PID=3641) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:26:03.829+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:26:03.830+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:26:03.830+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:26:03.840+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:26:03.838+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:26:03.840+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:26:03.857+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.033 seconds
[2023-02-27T09:26:34.212+0000] {processor.py:153} INFO - Started process (PID=3667) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:26:34.214+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:26:34.216+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:26:34.216+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:26:34.232+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:26:34.229+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:26:34.233+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:26:34.254+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.049 seconds
[2023-02-27T09:27:04.512+0000] {processor.py:153} INFO - Started process (PID=3705) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:27:04.515+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:27:04.517+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:27:04.516+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:27:04.527+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:27:04.526+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:27:04.528+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:27:04.547+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.042 seconds
[2023-02-27T09:27:34.819+0000] {processor.py:153} INFO - Started process (PID=3744) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:27:34.821+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:27:34.822+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:27:34.822+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:27:34.829+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:27:34.828+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:27:34.830+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:27:34.848+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.031 seconds
[2023-02-27T09:28:05.168+0000] {processor.py:153} INFO - Started process (PID=3770) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:28:05.169+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:28:05.170+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:28:05.170+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:28:05.179+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:28:05.177+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:28:05.180+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:28:05.197+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.032 seconds
[2023-02-27T09:28:35.415+0000] {processor.py:153} INFO - Started process (PID=3809) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:28:35.417+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:28:35.418+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:28:35.418+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:28:35.427+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:28:35.425+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:28:35.428+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:28:35.445+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.033 seconds
[2023-02-27T09:29:05.726+0000] {processor.py:153} INFO - Started process (PID=3846) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:29:05.729+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:29:05.731+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:29:05.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:29:05.745+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:29:05.743+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:29:05.746+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:29:05.770+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.049 seconds
[2023-02-27T09:29:36.084+0000] {processor.py:153} INFO - Started process (PID=3872) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:29:36.085+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:29:36.086+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:29:36.086+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:29:36.094+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:29:36.093+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:29:36.095+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:29:36.112+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.031 seconds
[2023-02-27T09:30:06.426+0000] {processor.py:153} INFO - Started process (PID=3912) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:30:06.429+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:30:06.431+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:30:06.431+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:30:06.445+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:30:06.442+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:30:06.446+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:30:06.467+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.047 seconds
[2023-02-27T09:30:36.746+0000] {processor.py:153} INFO - Started process (PID=3950) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:30:36.749+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:30:36.751+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:30:36.751+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:30:36.767+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:30:36.764+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:30:36.767+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:30:36.787+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.047 seconds
[2023-02-27T09:31:07.061+0000] {processor.py:153} INFO - Started process (PID=3978) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:31:07.062+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:31:07.063+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:31:07.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:31:07.073+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:31:07.071+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:31:07.074+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:31:07.095+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.037 seconds
[2023-02-27T09:31:37.380+0000] {processor.py:153} INFO - Started process (PID=4016) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:31:37.383+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:31:37.385+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:31:37.385+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:31:37.400+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:31:37.398+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:31:37.402+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:31:37.420+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.046 seconds
[2023-02-27T09:32:07.695+0000] {processor.py:153} INFO - Started process (PID=4052) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:32:07.699+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:32:07.700+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:32:07.700+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:32:07.712+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:32:07.711+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:32:07.713+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:32:07.732+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.044 seconds
[2023-02-27T09:32:38.037+0000] {processor.py:153} INFO - Started process (PID=4077) to work on /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:32:38.039+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2023-02-27T09:32:38.040+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:32:38.040+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:32:38.050+0000] {logging_mixin.py:137} INFO - [2023-02-27T09:32:38.048+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 7, in <module>
    default_args=default_args, catchup=False
NameError: name 'default_args' is not defined
[2023-02-27T09:32:38.051+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2023-02-27T09:32:38.069+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.036 seconds
